// frontend/src/components/FeedbackMessage.vue
<template>
  <div class="card">
    <!-- Result header with fresh colors -->
    <div class="p-5 text-center border-b" 
         :class="correct ? 'bg-gradient-to-r from-accent-500 to-accent-400 border-accent-600' : 'bg-gradient-to-r from-coral-500 to-coral-400 border-coral-600'">
      <div class="mb-3">
        <span v-if="correct" class="text-4xl">🎉</span>
        <span v-else class="text-3xl">😔</span>
      </div>
      
      <h3 class="text-xl font-bold text-white mb-2">
        {{ correct ? 'Correct!' : 'Not quite...' }}
      </h3>
      
      <p class="text-white text-opacity-90 text-lg">
        <span v-if="!correct">
          The correct answer is <span class="font-bold">{{ correctAnswer.city }}, {{ correctAnswer.country }}</span>
        </span>
        <span v-else>
          You guessed it! <span class="font-bold">{{ correctAnswer.city }}, {{ correctAnswer.country }}</span>
        </span>
      </p>
    </div>
    
    <!-- Fun fact section with fresh styling -->
    <div class="card-body">
      <div class="p-5 bg-gray-50 rounded-lg border border-gray-200">
        <div class="flex">
          <div class="flex-shrink-0 bg-white rounded-full p-2 shadow-sm mr-4">
            <span class="text-xl">💡</span>
          </div>
          
          <div>
            <h4 class="font-medium text-gray-900 mb-2">Fun Fact</h4>
            <p class="text-gray-700">{{ funFact }}</p>
          </div>
        </div>
      </div>
      
      <!-- Action buttons - Next and Challenge with consistent styling -->
      <div class="mt-5 flex flex-row gap-3 justify-center">
        <!-- Next button on the left -->
        <button @click="$emit('next')" 
                class="btn btn-primary">
          Next
        </button>
        
        <!-- Challenge button on the right - always visible for all users -->
        <button @click="$emit('challenge')" 
                class="btn btn-primary">
          Challenge a Friend
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { onMounted } from 'vue';

const props = defineProps({
  correct: {
    type: Boolean,
    required: true,
  },
  correctAnswer: {
    type: Object,
    required: true,
  },
  funFact: {
    type: String,
    required: true,
  },
});

defineEmits(['next', 'challenge']);

onMounted(() => {
  if (props.correct) {
    // More colorful confetti with our fresh palette
    import('canvas-confetti').then(module => {
      const confetti = module.default;
      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#25b6a6', '#2d8eff', '#f9654c', '#0c97e2']
      });
    });
  }
});
</script>

// frontendReact/src/components/FeedbackMessage.jsx
import React from 'react';
import { useSelector } from 'react-redux';
import { LightBulbIcon } from '@heroicons/react/24/outline';

const FeedbackMessage = ({ feedback, onNext, showChallengeButton, onChallenge }) => {
  const { correct, message, correctAnswer, funFact } = feedback;
  const { isAuthenticated } = useSelector((state) => state.user);

  // Set colors and emojis based on correct/incorrect
  const bgColor = correct ? 'bg-teal-500' : 'bg-red-500';
  const emoji = correct ? '🎉' : '😔';

  return (
    <div className="mt-6">
      {/* Top colored feedback section - full width with no borders */}
      <div className={`${bgColor} p-8 text-center text-white rounded-t-xl`}>
        <div className="mb-4">
          <span className="text-4xl">{emoji}</span>
        </div>
        <h3 className="text-3xl font-semibold mb-3">{message}</h3>
        {!correct && correctAnswer && (
          <p className="text-white text-xl">
            The correct answer is <span className="font-bold">{correctAnswer.city}, {correctAnswer.country}</span>
          </p>
        )}
        {correct && correctAnswer && (
          <p className="text-white text-xl">
            You guessed it! <span className="font-bold">{correctAnswer.city}, {correctAnswer.country}</span>
          </p>
        )}
      </div>

      {/* Container for Fun Fact and buttons */}
      <div className="bg-white rounded-b-xl border border-gray-200 border-t-0 shadow-lg">
        {/* Fun Fact section */}
        {funFact && (
          <div className="p-8 border-b border-gray-100">
            <div className="flex items-start">
              <div className="flex-shrink-0 bg-yellow-50 rounded-full p-3 mr-5">
                <span className="text-3xl">💡</span>
              </div>
              <div>
                <h4 className="text-xl font-semibold text-gray-800 mb-2">Fun Fact</h4>
                <p className="text-gray-700 text-lg">{funFact}</p>
              </div>
            </div>
          </div>
        )}

        {/* Buttons section */}
        <div className="p-6 flex flex-row justify-center gap-4">
          <button 
            onClick={onNext} 
            className="bg-blue-500 hover:bg-blue-600 text-white px-8 py-3 rounded-md font-medium text-lg transition-colors"
          >
            Next
          </button>
          {showChallengeButton && isAuthenticated && (
            <button 
              onClick={onChallenge}
              className="bg-blue-500 hover:bg-blue-600 text-white px-8 py-3 rounded-md font-medium text-lg transition-colors"
            >
              Challenge a Friend
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default FeedbackMessage;
