// frontendReact/src/components/AppHeader.jsx
import { Link, useLocation } from 'react-router-dom';
import { useSelector, useDispatch } from 'react-redux';
import { useState } from 'react';
import { logout, clearError } from '../stores/userSlice';
import { TrophyIcon, CheckCircleIcon, XCircleIcon, ArrowLeftOnRectangleIcon } from '@heroicons/react/24/solid';
import LoginPopup from './LoginPopup';

const AppHeader = () => {
  const { username, score: userTotalScore, isAuthenticated } = useSelector((state) => state.user);
  const { score: gameScore, correctAnswers, incorrectAnswers } = useSelector((state) => state.game);
  const dispatch = useDispatch();
  const location = useLocation();
  const [isLoginOpen, setIsLoginOpen] = useState(false);

  const isGameRoute = location.pathname.startsWith('/game');

  const handleLogout = () => {
    dispatch(logout());
  };

  const openLoginPopup = () => {
    dispatch(clearError()); // Clear any previous errors
    setIsLoginOpen(true);
  };

  const displayScore = isGameRoute ? gameScore : userTotalScore;

  return (
    <header className="bg-gradient-to-r from-blue-500 to-blue-600 shadow-md sticky top-0 z-50">
      <div className="container mx-auto px-4">
        <div className="flex justify-between items-center h-16">
          <div className="flex-1 flex justify-start items-center">
            <Link to="/" className="flex items-center text-white hover:opacity-90 transition-opacity">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
              </svg>
              <span className="text-xl font-bold">Globetrotter</span>
            </Link>
          </div>
          
          <div className="flex-shrink-0">
            <div className="bg-white/20 backdrop-blur-sm rounded-lg px-5 py-2 flex items-center justify-center space-x-6">
              <div className="flex items-center text-yellow-300" title="Score">
                <TrophyIcon className="h-5 w-5 mr-1.5" />
                <span className="font-bold text-white text-sm sm:text-base">{isAuthenticated ? displayScore : '0'}</span>
              </div>
              <div className="flex items-center text-green-400" title="Correct Answers">
                <CheckCircleIcon className="h-5 w-5 mr-1.5" />
                <span className="font-bold text-white text-sm sm:text-base">{isAuthenticated ? correctAnswers : '0'}</span>
              </div>
              <div className="flex items-center text-red-400" title="Incorrect Answers">
                <XCircleIcon className="h-5 w-5 mr-1.5" />
                <span className="font-bold text-white text-sm sm:text-base">{isAuthenticated ? incorrectAnswers : '0'}</span>
              </div>
            </div>
          </div>

          <div className="flex-1 flex justify-end items-center">
            {isAuthenticated ? (
              <div className="flex items-center space-x-3">
                <span className="text-white font-medium mr-2 truncate max-w-[120px]" title={username}>{username}</span>
                <button 
                  onClick={handleLogout}
                  className="bg-white/10 hover:bg-white/20 rounded-full p-2 text-white transition-colors"
                  title="Sign out"
                >
                  <ArrowLeftOnRectangleIcon className="h-5 w-5"/>
                </button>
              </div>
            ) : (
              <button
                onClick={openLoginPopup}
                className="bg-white text-blue-600 hover:bg-blue-50 px-6 py-2 rounded-md text-base font-medium transition-colors shadow-sm"
              >
                Sign In
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Login Popup */}
      <LoginPopup isOpen={isLoginOpen} onClose={() => setIsLoginOpen(false)} />
    </header>
  );
};

export default AppHeader;

// frontend/src/components/AppHeader.vue
<template>
  <header class="bg-gradient-to-r from-primary-600 via-primary-500 to-secondary-500 shadow-md">
    <div class="container mx-auto px-4 py-3">
      <!-- Three-column layout -->
      <div class="flex justify-between items-center">
        <!-- Logo section (left) -->
        <div class="w-1/4">
          <router-link to="/" class="flex items-center">
            <div class="mr-3">
              <span class="text-2xl">🌍</span>
            </div>
            <h1 class="text-xl font-bold text-white hidden sm:block">Globetrotter</h1>
          </router-link>
        </div>
        
        <!-- Game stats (center - using 2/4 for emphasis) -->
        <div class="w-2/4 flex justify-center">
          <!-- Logged in user stats -->
          <div v-if="userStore.isLoggedIn" 
               class="bg-white/10 backdrop-blur-sm rounded-lg px-4 py-2 flex items-center justify-center shadow-inner">
            <div class="flex items-center space-x-6">
              <div class="flex items-center text-yellow-300">
                <span class="text-xl mr-2">🏆</span>
                <span class="font-bold">{{ userStore.score }}</span>
              </div>
              <div class="flex items-center text-green-300">
                <span class="text-xl mr-2">✅</span>
                <span class="font-bold">{{ userStore.correctAnswers }}</span>
              </div>
              <div class="flex items-center text-red-300">
                <span class="text-xl mr-2">❌</span>
                <span class="font-bold">{{ userStore.totalAttempts - userStore.correctAnswers }}</span>
              </div>
            </div>
          </div>
          
          <!-- Anonymous user stats - Changed condition to check attempts instead of score -->
          <div v-else-if="anonymousAttempts > 0" 
               class="bg-white/10 backdrop-blur-sm rounded-lg px-4 py-2 flex items-center justify-center shadow-inner">
            <div class="flex items-center space-x-6">
              <div class="flex items-center text-yellow-300">
                <span class="text-xl mr-2">🏆</span>
                <span class="font-bold">{{ anonymousScore }}</span>
              </div>
              <div class="flex items-center text-green-300">
                <span class="text-xl mr-2">✅</span>
                <span class="font-bold">{{ anonymousCorrectAnswers }}</span>
              </div>
              <div class="flex items-center text-red-300">
                <span class="text-xl mr-2">❌</span>
                <span class="font-bold">{{ anonymousAttempts - anonymousCorrectAnswers }}</span>
              </div>
            </div>
          </div>
          
          <!-- Current game info when playing -->
          <div v-else-if="gameStore.currentScore > 0" 
               class="bg-white/10 backdrop-blur-sm rounded-lg px-4 py-2 flex items-center shadow-inner">
            <div class="text-white font-bold">
              Score: {{ gameStore.currentScore }}
              <span v-if="gameStore.streak > 1" class="ml-2 text-orange-300">
                🔥 {{ gameStore.streak }}
              </span>
            </div>
          </div>
        </div>
        
        <!-- User profile (right) -->
        <div class="w-1/4 flex justify-end">
          <div v-if="userStore.isLoggedIn" class="flex items-center">
            <span class="hidden md:inline text-white font-medium mr-2">{{ userStore.username }}</span>
            <button 
              @click="logout" 
              class="bg-white/20 hover:bg-white/30 rounded-full p-2 text-white"
              title="Sign out"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M3 3a1 1 0 00-3 3v8a1 1 0 003 3h10a1 1 0 003-3V6a1 1 0 00-3-3H3zm11 8a1 1 0 100-2H6.414l1.293-1.293a1 1 0 10-1.414-1.414l-3 3a1 1 0 000 1.414l3 3a1 1 0 001.414-1.414L6.414 11H14z" />
              </svg>
            </button>
          </div>
          
          <!-- Sign in button if not logged in -->
          <button v-else 
                  @click="$emit('show-login')" 
                  class="bg-white text-primary-600 hover:bg-primary-50 px-4 py-2 rounded-lg text-sm font-medium transition-colors shadow-sm">
            Sign In
          </button>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup>
import { ref } from 'vue';
import { useUserStore } from '@/stores/user';
import { useGameStore } from '@/stores/game';
import { useRouter } from 'vue-router';

const props = defineProps({
  // Add props for anonymous stats
  anonymousScore: {
    type: Number,
    default: 0
  },
  anonymousCorrectAnswers: {
    type: Number,
    default: 0
  },
  anonymousAttempts: {
    type: Number,
    default: 0
  }
});

const userStore = useUserStore();
const gameStore = useGameStore();
const router = useRouter();

const logout = () => {
  userStore.logout();
  if (router.currentRoute.value.path !== '/') {
    router.push('/');
  }
};
</script>
