// frontendReact/src/components/DestinationClue.jsx
import { GlobeAltIcon } from '@heroicons/react/24/solid';

const DestinationClue = ({ clue }) => {
  // Simple check if clue is an array (for multiple clues) or string
  const clues = Array.isArray(clue) ? clue : [clue]; 

  return (
    <div className="p-6 bg-blue-50 rounded-2xl border border-blue-100 mb-6">
      <div className="flex items-center text-blue-600 mb-5">
        <GlobeAltIcon className="h-6 w-6 mr-2 flex-shrink-0" />
        <h2 className="text-xl font-semibold">Where is this place?</h2>
      </div>
      
      <div className="space-y-4">
        {clues.map((c, index) => (
          <div key={index} className="bg-white rounded-lg p-4 border border-blue-100">
            <div className="flex items-start">
              <span className="text-blue-600 font-medium mr-3">Clue {index + 1}:</span>
              <p className="text-gray-700 flex-1 italic">{c}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default DestinationClue;

// frontend/src/components/DestinationClue.vue
<template>
  <div class="card">
    <!-- Header with fresh gradient -->
    <div class="card-header">
      <h2 class="flex items-center text-lg font-medium text-primary-800">
        <span class="text-xl mr-2">🌍</span>
        Where is this place?
      </h2>
    </div>
    
    <!-- Clues section with larger text -->
    <div class="card-body">
      <div class="space-y-4">
        <div v-for="(clue, index) in clues" :key="index" class="clue-card">
          <div class="flex">
            <div class="text-accent-600 font-medium mr-3">Clue {{ index + 1 }}:</div>
            <p class="text-gray-700 italic flex-grow">
              "{{ clue }}"
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  clues: {
    type: Array,
    required: true,
  },
});
</script>
